sudo: required

language: node_js
node_js:
  - "6"
python:
  - "3.4"

notifications:
  email: false

cache:
  pip: true
  directories:
    - node_modules

before_install:
  - sudo apt-get install -y python3.4
  - sudo apt-get install --upgrade -y python-pip

install:
  - npm install
  - pip install awscli

script:
  - npm run build-prod

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS
  secret_access_key: $AWS_SECRET
  bucket: $S3_BUCKET
  region: $AWS_REGION
  local_dir: dist
  skip_cleanup: true
  acl: public_read
  
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"